CREATE DATABASE IF NOT EXISTS messages;

USE messages;

CREATE TABLE IF NOT EXISTS datas (
    id VARCHAR(255) PRIMARY KEY,
    message VARCHAR(2048) NOT NULL
);
GRANT SELECT, UPDATE, INSERT, DELETE ON messages.* TO 'admin'@'%';

FLUSH PRIVILEGES;